[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "numeric"
version = "0.1.0"
dependencies = [
  "numpy",
  "plotly",
  "nbformat",
  "ipython",
  "ipykernel"
]
requires-python = ">=3.10"

[tool.setuptools.packages]
find = {}